name: Deploy .NET API to IIS

# Chạy tự động khi có code đẩy lên nhánh master
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: 📥 Tải source code mới nhất về Server
      uses: actions/checkout@v4

    - name: 🛠️ Cài đặt môi trường .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: ⚙️ Build và Publish code Backend
      run: dotnet publish -c Release -o ./publish_output

    - name: 🛑 Dừng ứng dụng trên IIS (Chống lỗi khóa file & Trạng thái)
      shell: powershell
      run: |
        Import-Module WebAdministration
        $state = (Get-WebAppPoolState -Name "apiqlhsba").Value
        if ($state -eq "Started") {
            Stop-WebAppPool -Name "apiqlhsba"
            Start-Sleep -Seconds 5
            Write-Host "Da tat App Pool thanh cong va cho 5s."
        } else {
            Write-Host "App Pool da dung san, bo qua buoc tat."
        }

    - name: 🚀 Copy file đè lên thư mục web IIS
      shell: powershell
      run: Copy-Item -Path ./publish_output/* -Destination "C:\inetpub\wwwroot\api_qlba" -Recurse -Force

    - name: 🟢 Khởi động lại ứng dụng trên IIS
      shell: powershell
      run: |
        Import-Module WebAdministration
        $state = (Get-WebAppPoolState -Name "apiqlhsba").Value
        if ($state -ne "Started") {
            Start-WebAppPool -Name "apiqlhsba"
            Write-Host "Da khoi dong lai App Pool."
        } else {
            Write-Host "App Pool dang chay san roi."
        }